### ISSUE TITLE
请问vscode可以使用acllib图形库吗？应该如何配置环境？

### ISSUE THREAD

**Issue by FranShavee** [Satoing/Battle-of-Balls#1]
我在vscode中使用json文件，cmake的cmakelists配置都没成功，acllib.c库文件会显示有些错误，编译时提示没有undefine reference to winmain等错误

**Comment by Satoing** [comment]
可以，直接在命令行中用g++等编译器编译运行即可，链接的时候把官方的`acllib.a`（静态链接库）链接到可执行文件里面就行了。
我没用过cmake，因为我习惯直接写`makefile`，所以不是很清楚使用cmake的坑。不过我觉得你可以看看我的代码结构。
如果你用的也是g++编译器，你可以尝试把我的代码clone下来运行一下。编译命令就是makefile中的`g++ -o bin/main src/*.cpp lib/acllib.a -lm -lgdi32 -lole32 -loleaut32 -luuid -lwinmm -lmsimg32 -Iinclude -g -fexec-charset=GBK`。你也可以直接使用`make`来运行，可执行文件将会输出到`bin`目录中。
另外，vscode中json文件的配置不是必要的，不过最好还是在里面添加头文件的搜索路径，方便代码的自动提示。

**Comment by Satoing** [comment]
对了，这段说明应该可以方便你理解：
![image](https://user-images.githubusercontent.com/68995451/203944990-682ca998-67af-4b1d-b6cc-11e851248a9f.png)
将`acllib.c`编译为`acllib.a`的命令是`gcc -c acllib.c`

**Comment by FranShavee** [comment]
![image](https://user-images.githubusercontent.com/113026031/203956846-f6e27952-1248-4609-93d1-0e5a9914f0b5.png)
![image](https://user-images.githubusercontent.com/113026031/203956586-f07ce246-1979-4c2f-b2d5-c6a4b89c6ad6.png)
make run后显示undefine reference这样的一系列错误

**Comment by Satoing** [comment]
我觉得是mingw的问题，看起来你的mingw是64位？我用的是32位。所以你重新编译一下acllib.c吧。
![image](https://user-images.githubusercontent.com/68995451/203967761-1464c0f5-8423-4cf1-8f91-863b1b25c323.png)

**Comment by FranShavee** [comment]
![image](https://user-images.githubusercontent.com/113026031/203972529-3d609cdc-3fdb-43bf-be08-84053d955cf2.png)
出现了这样的报错

**Comment by Satoing** [comment]
把`acllib.c`和`acllib.h`放到同一个文件夹下再编译，因为`acllib.c`是以相对路径的方式引入头文件的：`#include "acllib.h"`

**Comment by FranShavee** [comment]
成功了，十分感谢
